# Generated by Django 5.0.6 on 2024-05-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to=None)),
                ('member_since', models.DateField()),
                ('first_tournament', models.DateField(default=None)),
                ('tournament_participation', models.IntegerField(default=0)),
                ('role', models.ManyToManyField(to='Lice.liceposition')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='Lice.skilldomain')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques_levels', to='Lice.fighter')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lice.technique')),
            ],
        ),
    ]
