# Generated by Django 5.0.6 on 2024-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='first_tournament',
            field=models.DateField(blank=True),
        ),
    ]
