# Generated by Django 5.0.6 on 2024-05-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0003_alter_fighter_first_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='picture',
            field=models.ImageField(blank=True, upload_to='fighterspictures/'),
        ),
    ]
