# Generated by Django 5.0.6 on 2024-05-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0005_enemyteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('localization', models.CharField(blank=True, max_length=100, null=True)),
                ('ranking', models.IntegerField()),
                ('number_of_match', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_rank', models.IntegerField()),
                ('number_of_round', models.IntegerField()),
                ('enemyteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lice.enemyteam')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='Lice.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_rank', models.IntegerField()),
                ('fighters_involved', models.ManyToManyField(to='Lice.fighter')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='Lice.match')),
            ],
        ),
        migrations.CreateModel(
            name='RoundPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_on_the_ground', models.BooleanField()),
                ('takedown_solo', models.IntegerField(default=0)),
                ('takedown_team', models.IntegerField(default=0)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lice.fighter')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lice.round')),
            ],
        ),
    ]
