# Generated by Django 5.0.6 on 2024-05-31 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0007_roundperformance_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundperformance',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lice.liceposition'),
        ),
    ]
