# Generated by Django 5.0.6 on 2024-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0009_alter_match_tournament_alter_round_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='victory',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='round',
            name='issue',
            field=models.CharField(blank=True, choices=[('V', 'victory'), ('DE', 'defeat'), ('DR', 'draw')], max_length=8),
        ),
        migrations.AddField(
            model_name='roundperformance',
            name='armor_default',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundperformance',
            name='double_chute',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='roundperformance',
            name='resistance_level',
            field=models.CharField(blank=True, choices=[('B', 'bad'), ('M', 'medium'), ('G', 'good'), ('LS', 'last standing')], max_length=15),
        ),
        migrations.AddField(
            model_name='skilldomain',
            name='color',
            field=models.CharField(blank=True, default='#925040', max_length=7),
        ),
    ]
