# Generated by Django 5.0.6 on 2024-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0010_match_victory_round_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundperformance',
            name='armor_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
