# Generated by Django 5.0.6 on 2024-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0011_alter_roundperformance_armor_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldomain',
            name='color',
            field=models.CharField(default='#925040', max_length=7),
        ),
    ]
