# Generated by Django 5.0.6 on 2024-06-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0012_alter_skilldomain_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='victory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='issue',
            field=models.CharField(choices=[('V', 'victory'), ('DE', 'defeat'), ('DR', 'draw')], max_length=8),
        ),
    ]
