# Generated by Django 5.0.6 on 2024-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0013_alter_match_victory_alter_round_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='victory',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='roundperformance',
            name='armor_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roundperformance',
            name='double_chute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roundperformance',
            name='first_on_the_ground',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roundperformance',
            name='resistance_level',
            field=models.CharField(choices=[('B', 'bad'), ('M', 'medium'), ('G', 'good'), ('LS', 'last standing')], max_length=15),
        ),
    ]
