# Generated by Django 5.0.6 on 2024-06-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0014_alter_match_victory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='role',
            field=models.ManyToManyField(blank=True, to='Lice.liceposition'),
        ),
    ]
