# Generated by Django 5.0.6 on 2024-07-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0016_alter_roundperformance_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundperformance',
            name='armor_default',
        ),
        migrations.RemoveField(
            model_name='roundperformance',
            name='fighter',
        ),
        migrations.RemoveField(
            model_name='roundperformance',
            name='round',
        ),
        migrations.AddField(
            model_name='roundperformance',
            name='fighterID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='roundperformance',
            name='roundID',
            field=models.IntegerField(null=True),
        ),
    ]
