# Generated by Django 5.0.6 on 2024-07-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0017_remove_roundperformance_armor_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundperformance',
            name='fighterID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roundperformance',
            name='roundID',
            field=models.IntegerField(),
        ),
    ]
