# Generated by Django 5.0.6 on 2024-07-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0019_alter_roundperformance_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundperformance',
            name='position',
            field=models.IntegerField(),
        ),
    ]
