# Generated by Django 5.0.6 on 2024-07-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0020_alter_roundperformance_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundperformance',
            old_name='position',
            new_name='positionID',
        ),
    ]
