# Generated by Django 5.0.6 on 2024-07-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lice', '0021_rename_position_roundperformance_positionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundperformance',
            old_name='positionID',
            new_name='lice_position_position',
        ),
    ]
